services:
  - type: web
    name: balneabilidade-fortaleza-api
    env: python
    plan: free
    # Define a versão do Python aqui
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app